version: "3"

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - WAIT_HOSTS=mongo
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app/back-end # Volume pour le backend

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app/front-end # Volume pour le front-end
      - /app/front-end/node_modules
